### PR TITLE
Support for Github Actions

### PR DESCRIPTION
**Pull request by gaby**
The purpose of this PR is to automate the testing of new PR's and code changes to `StoreDown`

It seems like some code changes need to happen, since `npm build` is failing with the following: 

```
This relative module was not found:

* ../../../storedown-common/Database.js in ./src/services/Database.js
```

Unless I'm missing something?

### CODE REVIEW

**Comment by gaby** [comment]
@FoxUSA I have several questions: 

* Should I keep support for `macos` and `windows` during this test?
* Do you know why `npm build` is complaining about `relative paths`? 

I basically tried to simulate the same commands you have in https://github.com/FoxUSA/StoreDown/blob/master/docs/development.md

**Comment by gaby** [comment]
I can't seem to find `../../../storedown-common/Database.js` in the source code.

**Comment by gaby** [comment]
The development.md states to run `npm run install` but that command doesn't exist.

**Comment by FoxUSA** [comment]
@gaby we can trade mistakes. I forgot a file. In your command you added run. It should be just `npm install`. I checked and that is what is in the docs.

This file use to be in its own module because I intended to abstract shared code out for use in a cli and plugins like an Alexa skill. That work tree died out so I just included the function.

**Comment by gaby** [comment]
Awesome @FoxUSA can you approve the workflow, to see if it passes?

**Comment by gaby** [comment]
I'm running the CI here https://github.com/gaby/StoreDown/runs/6149642317?check_suite_focus=true

So far everything went fine until `npm run test:unit` were it fails

**Comment by gaby** [comment]
I just removed the unit:test stage since it's not actually doing anything. Running the e2e on GitHub requires a separate PR.

For now this PR is: 

* Installing dependencies
* Running npm build
* Running lint test

Should be good to merge :-)

**Comment by FoxUSA** [comment]
@gaby 
I will accept this pull request if it is given under a MIT License

**Comment by gaby** [comment]
@FoxUSA Yes, it's under MIT License, same as this repo.

**Comment by FoxUSA** [comment]
@gaby thank you for working on this.

**Pull request merged**
